# <?php die(); ?>

## 注意：书写时，缩进不能使用 Tab，必须使用空格

#############################
# 数据库设置
#############################

# devel 模式
devel:
  driver:     mysql
  host:       127.0.0.1
  login:      root
  password:   @c6688*z
  database:   cms
  charset:    utf8
  prefix:     cms_

# test 模式
test:
  driver:     mysql
  host:       127.0.0.1
  login:      root
  password:   @c6688*z
  database:   cms
  charset:    utf8
  prefix:     cms_

# deploy 模式
deploy:
  driver:     mysql
  host:       127.0.0.1
  login:      root
  password:   @c6688*z
  database:   cms
  charset:    utf8
  prefix:     cms_
